"""
Application constants
"""

# Market codes
MARKET_CODE_KOSPI = "J"
MARKET_CODE_KOSDAQ = "Q"
MARKET_CODE_KONEX = "K"

# TR IDs
TR_ID_CONDITION_LIST = "HHKST03900300"  # 조건검색 목록 조회
TR_ID_CONDITION_SEARCH = "HHKST03900400"  # 조건검색 실행
TR_ID_STOCK_PRICE = "FHKST01010100"  # 주식 현재가 시세
TR_ID_STOCK_DAILY = "FHKST01010400"  # 주식 일봉 조회
TR_ID_STOCK_MINUTE = "FHKST01010600"  # 주식 분봉 조회

# API Rate Limits
RATE_LIMIT_PER_SECOND = 20
RATE_LIMIT_PER_MINUTE = 1000
MIN_REQUEST_INTERVAL = 0.05  # 50ms

# Market Hours (KST)
MARKET_OPEN_HOUR = 9
MARKET_OPEN_MINUTE = 0
MARKET_CLOSE_HOUR = 15
MARKET_CLOSE_MINUTE = 30

# Status codes
STATUS_SUCCESS = "success"
STATUS_FAILED = "failed"
STATUS_PENDING = "pending"

# Notification types
NOTIFICATION_CONSOLE = "console"
NOTIFICATION_SLACK = "slack"
NOTIFICATION_EMAIL = "email"
